
const input = [
  {
    "json": {
      "Like": 58,
      "CM": 14,
      "VideoURL": "https://www.instagram.com/p/DRw9qBmiGXw/",
      "Caption": "📘گاهی می‌پرسیم..."
    }
  },
  {
    "json": {
      "Like": 75,
      "CM": 82,
      "VideoURL": "https://www.instagram.com/p/DRxDoFoEUCj/",
      "Caption": "خطاهای شناختی..."
    }
  },
  {
    "json": {
      "Like": "",
      "CM": "",
      "VideoURL": "",
      "Caption": "",
      "debug_status": "No new unique reels found"
    }
  },
  {
    "json": {
      "Like": 1441,
      "CM": 77,
      "VideoURL": "https://www.instagram.com/p/DQh38AajZrb/",
      "Caption": "بدترین حس..."
    }
  }
];

const $input = {
    all: () => input
};

// --- Corrected Format Email Logic ---
// Get all items from the previous node
const items = $input.all().map(i => i.json);

// Filter out invalid items (e.g. those with empty VideoURL)
const validItems = items.filter(item => item.VideoURL && item.VideoURL.toString().trim() !== '');

// 1. Convert counts to numbers and Sort by Likes (Descending)
validItems.sort((a, b) => {
  const likesA = parseInt(a.Like || 0);
  const likesB = parseInt(b.Like || 0);
  return likesB - likesA;
});

// 2. Take Top 10
const top10 = validItems.slice(0, 10);

// 3. Generate HTML
let html = `
<div style="font-family: Arial, sans-serif; color: #333;">
  <h2 style="color: #E1306C;">🔥 ریلزهای پربازدید پیدا شد!</h2>
  <p>بفرمایید, لیست ریلزهای پربازدید مرتبط به ترتیب تعداد لایک :</p>
  <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
    <thead>
      <tr style="background-color: #f4f4f4; text-align: left;">
        <th style="padding: 12px; border-bottom: 2px solid #ddd;">Post</th>
        <th style="padding: 12px; border-bottom: 2px solid #ddd;">Likes</th>
        <th style="padding: 12px; border-bottom: 2px solid #ddd;">Comments</th>
        <th style="padding: 12px; border-bottom: 2px solid #ddd;">Link</th>
      </tr>
    </thead>
    <tbody>
`;

for (const item of top10) {
  const caption = item.Caption ? item.Caption.substring(0, 100) + (item.Caption.length > 100 ? '...' : '') : 'No Caption';
  const link = item.VideoURL || '#';

  html += `
      <tr style="border-bottom: 1px solid #eee;">
        <td style="padding: 12px; vertical-align: top;">
            <strong>${caption}</strong><br>
            <span style="font-size: 12px; color: #888;">${item.searchedHashtag || ''}</span>
        </td>
        <td style="padding: 12px; font-weight: bold; color: #E1306C;">${parseInt(item.Like || 0).toLocaleString()}</td>
        <td style="padding: 12px;">${parseInt(item.CM || 0).toLocaleString()}</td>
        <td style="padding: 12px;">
            <a href="${link}" style="background-color: #0095f6; color: white; padding: 8px 12px; text-decoration: none; border-radius: 4px; font-size: 12px;">View Post</a>
        </td>
      </tr>
  `;
}

html += `
    </tbody>
  </table>
  <p style="margin-top: 20px; font-size: 12px; color: #888;">Generated by n8n Viral Scraper</p>
</div>
`;

console.log(JSON.stringify([{
  json: {
    subject: `🚀 ۱۰ ریلز وایرال - ${new Date().toLocaleDateString()}`,
    html_body: html
  }
}], null, 2));
